apiVersion: v1
kind: Service
metadata:
  name: udagram-reverseproxy-app
  labels:
    app: udagram-reverseproxy-app
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: udagram-reverseproxy-app