apiVersion: v1
kind: Service
metadata:
  name: backend-feed
  labels:
    app: udagram-feed-app
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: udagram-feed-app