apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-feed-app
  labels:
    app: udagram-feed-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-feed-app
  template:
    metadata:
      labels:
        app: udagram-feed-app
    spec:
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret   
      containers:
      - name: udagram-api-feed
        image: emanfawzy499/udagram-api-feed:v9
        envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: env-secret
        volumeMounts:
          - name: aws-secret
            readOnly: true     
            mountPath: "/root/.aws/"
        ports:
          - containerPort: 8080           