apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-feed-app
  labels:
    app: udagram-feed-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-feed-app
  template:
    metadata:
      labels:
        app: udagram-feed-app
    spec:
      containers:
      - name: udagram-api-feed
        image: emanfawzy499/udagram-api-feed:v6
        envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: env-secret     
        - secretRef:
            name: aws-secret       
        ports:
          - containerPort: 8080              